### ISSUE TITLE
Missing Dependency

### ISSUE THREAD

**Issue by carlschroedl** [MinnPost/jquery-vertical-timeline#15]
@zzolo , bower.json lists "https://github.com/zzolo/tabletop.git#timeline-fixes" as a dependency of this project. The repo no longer exists. Could you please restore the repo or point me to an alternative?

**Comment by zzolo** [comment]
Sorry about that.  We are working on a re-write right now which will fix this.  Will let you know how it goes.

In the mean time, you should probably be able to just use the regular Tabletop.

**Comment by carlschroedl** [comment]
No worries. Thanks for open-sourcing this tool and for the speedy response. I will try regular Tabletop.

**Comment by gddabe** [comment]
How to use the regular tabletop during "bower install jquery-vertical-timeline -S" ?

**Comment by zzolo** [comment]
You should be able to do `bower install tabletop` and it should get the current version.

**Comment by tnehil** [comment]
I've updated the code here 529a2e3632502e51bf568c27fdd0ef5985732e87 to just use the latest version of tabletop, rather than the missing customized version. This appears to work in that it allows you to `bower install` w/o fatal errors, and I was able to get timelines working fine.
