### ISSUE TITLE
Proxy is gone

### ISSUE THREAD

**Issue by MuTLY** [MinnPost/jquery-vertical-timeline#18]
On the example page, the proxy located at `http://gs-proxy.herokuapp.com/proxy` is gone.

Not Found
The requested URL was not found on the server.
If you entered the URL manually please check your spelling and try again.

**Comment by zzolo** [comment]
Unfortunately TabletopJS and Google Spreadsheets keeps changing.

This project is not actively being maintained.  You might want to look at a new version (complete re-write):
http://datanews.github.io/tik-tok/

**Comment by MuTLY** [comment]
Will do. Thanks.
